name: Deploy StackIt SDK API Nestjs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.7.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
          node-version: 19.7.0
      - name: npm install and build
        run: |
          corepack enable
          yarn install
          yarn run build
        env:
          CI: true
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
            . ~/.nvm/nvm.sh
             nvm instal 19.7.0
             npm install -g pm2
             cd ~/stackit-sdk-nestjs
             git pull
             corepack enable
             yarn install
             yarn build
             pm2 restart ecosystem.config.js
